# /ui/lang_config.py

LANG = {
    "ja": {
        "login_title": "🔐 JIRA QA Bot ログイン",
        "user_id": "ユーザーID",
        "password": "パスワード",
        "login_btn": "ログイン",
        "login_success": "ようこそ、{user} さん！",
        "login_error": "IDまたはパスワードが間違っています。",
        "logout": "ログアウト",
        "logged_in": "ログイン中: {user}",
        "qa_title": "💬 JIRA QA Bot",
        "input_placeholder": "例：「この機能の仕様は？」",
        "input_label": "運用保守に関して知りたいことを入力してください",
        "ask_btn": "❓ 質問する",
        "loading": "回答を生成中...しばらくお待ちください",
        "answer": "✅ 回答:",
        "ref_info": "📚 参考JIRA/ドキュメント情報",
        "ticket_id": "対象チケット",
        "title": "タイトル",
        "status": "ステータス",
        "relevance": "関連度",
        "api_error": "APIエラーが発生しました",
        "refine_error": "質問の整形に失敗しました",
        "conn_error": "接続エラーが発生しました",
        "history": "🕘 質問履歴",
        "clear_btn": "🗑️ 履歴をすべて削除する",
        "cleared": "履歴を削除しました",
        "user": "ユーザー",
        "time": "日時",
        "prompt_type_label": "プロンプトタイプを選んでください",
        "prompt_type_detail": "詳細回答ver",
        "prompt_type_simple": "簡易回答ver",
        "disclaimer": "本回答は必ずしも正しいとは限りません。正確な情報は参考文献をご確認ください。"
    },
    "en": {
        "login_title": "🔐 JIRA QA Bot Login",
        "user_id": "User ID",
        "password": "Password",
        "login_btn": "Log In",
        "login_success": "Welcome, {user}!",
        "login_error": "Incorrect ID or password.",
        "logout": "Log Out",
        "logged_in": "Logged in as: {user}",
        "qa_title": "💬 JIRA QA Bot",
        "input_placeholder": 'e.g. "What are the specs of this feature?"',
        "input_label": "Enter your questions about operations and maintenance",
        "ask_btn": "❓ Ask",
        "loading": "Generating answer... please wait",
        "answer": "✅ Answer:",
        "ref_info": "📚 Reference JIRA / Documentation Info",
        "ticket_id": "Ticket ID",
        "title": "Title",
        "status": "Status",
        "relevance": "Relevance",
        "api_error": "API error occurred",
        "refine_error": "Failed to refine the question.",
        "conn_error": "Connection error occurred.",
        "history": "🕘 Question History",
        "clear_btn": "🗑️ Clear All History",
        "cleared": "History cleared.",
        "user": "User",
        "time": "Time",
        "prompt_type_label": "Select prompt type",
        "prompt_type_detail": "Detailed Answer",
        "prompt_type_simple": "Simple Answer",
        "disclaimer": "This response may not always be accurate. Please refer to the source documents for correct information."
    },
}
